version: "3.7"
services:
  mongo:
    image: mongo:4.2.10
    restart: on-failure
    ports: 
      - 27017:27017
    logging:
      driver: none
  api:
    image: challenge-express
    restart: on-failure
    build: ./challenge-express
    ports: 
      - 3000:3000
    environment:
      - APPLICATION_PORT=3000
      - MONGO_ENDPOINT=mongodb://mongo:27017
    depends_on: 
      - mongo
  next:
    image: challenge-next
    restart: on-failure
    build: ./challenge-next
    ports: 
      - 80:80
    environment:
      - BACKEND_API_URL=http://api:3000
      - BACKEND_API_KEY=hDb0Euw9wKYBk6vr26Gr816x7ITSFeE1
    depends_on: 
      - mongo
      - api